### PR TITLE
Add riemann-tools to nixpkgs

### PR DESCRIPTION
**Pull request by trentonstrong**
Adds package via bundlerEnv and service for Riemann health.

### CODE REVIEW

**Comment by shlevy** [comment]
Any reason not to open against upstream?

**Comment by trentonstrong** [comment]
Wanted to get your approval and such first!  We made some guesses as to where to place the package, and the ids.nix changes were a bit of cargo culting.

**Comment by shlevy** [comment]
OK! Will review tomorrow.

**Comment by trentonstrong** [comment]
Awesome, thanks @shlevy !

**Comment by rbxbx** [comment]
Thanks @shlevy !

**Comment by shlevy** [comment]
Merged upstream then fast-forwarded our master to upstream's

**Comment by rbxbx** [comment]
Thanks!

**Pull request merged**
